from app.config.settings import (
    BASE_DIR,
    FAISS_INDEX_PATH,
    METADATA_DIR,
    EMBEDDING_MODEL_NAME,
    EMBEDDING_DIM,
    DEFAULT_TOP_K,
    DEFAULT_NPROBE,
    MAX_HISTORY_TURNS,
    GEMINI_API_KEY,
    GEMINI_MODEL_NAME
)


print("BASE_DIR:", BASE_DIR)
print("FAISS_INDEX_PATH:", FAISS_INDEX_PATH)
print("METADATA_DIR:", METADATA_DIR)

print("EMBEDDING_MODEL_NAME:", EMBEDDING_MODEL_NAME)
print("EMBEDDING_DIM:", EMBEDDING_DIM)

print("DEFAULT_TOP_K:", DEFAULT_TOP_K)
print("DEFAULT_NPROBE:", DEFAULT_NPROBE)

print("MAX_HISTORY_TURNS:", MAX_HISTORY_TURNS)

print("GEMINI_MODEL_NAME:", GEMINI_MODEL_NAME)
print(
    "GEMINI_API_KEY loaded:",
    GEMINI_API_KEY is not None
)