
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

categories.page_size=10
categories.max_page_size=20
documents.page_size=10
documents.max_page_size=20