
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

categories.page_size=10
categories.max_page_size=20
documents.page_size=10
documents.max_page_size=20
admin.documents.page_size=10
admin.documents.max_page_size=20
users.page_size = 10
users.max_page_size = 20
bookmarks.page_size = 10
bookmarks.max_page_size = 20
reviews.page_size = 10
reviews.max_page_size = 20
notifications.page_size=10
notifications.max_page_size=20
