
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

categories.page_size=10
categories.max_page_size=20
documents.page_size=10
documents.max_page_size=20
admin.documents.page_size=10
admin.documents.max_page_size=20
users.page_size = 10
users.max_page_size = 20
bookmarks.page_size = 10
bookmarks.max_page_size = 20
reviews.page_size = 10
reviews.max_page_size = 20
notifications.page_size=10
notifications.max_page_size=20

stripe.secret_key=sk_test_51TdpRfAztn137noRNQufzfdyb1pAqIxuJREDsb77jH7KEg508yf8Syw6kgDEZ4QIvUQfBOCOqb6VDtwhXIiGWRUc007nVf2Xd4
stripe.webhook_secret=whsec_b62601e004911fbf983d461e3ea018a9f4ba0da0ef95636e7104c350fbd677da
stripe.currency=vnd

stripe.success_url=http://localhost:3000/payment/success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel_url=http://localhost:3000/payment/cancel
